FROM ypenglyn/hadoop:2.6.5

####################
# SPARK
####################

ENV SPARK_VERSION 2.1.0
ENV SPARK_HOME    /usr/local/spark
ENV SPARK_OPTS    -Djava.library.path=/usr/local/hadoop/lib/native
ENV HADOOP_BASE_VERSION 2.6
ENV PATH          $PATH:$SPARK_HOME/bin:$SPARK_HOME/sbin

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install curl && \
    curl -O http://d3kbcqa49mib13.cloudfront.net/spark-$SPARK_VERSION-bin-hadoop$HADOOP_BASE_VERSION.tgz && \
    apt-get remove -y curl && \
    tar -zxf /spark-$SPARK_VERSION-bin-hadoop$HADOOP_BASE_VERSION.tgz && \
    rm /spark-$SPARK_VERSION-bin-hadoop$HADOOP_BASE_VERSION.tgz && \
    mv spark-$SPARK_VERSION-bin-hadoop$HADOOP_BASE_VERSION /usr/local/spark && \
    mkdir -p /usr/local/spark/logs

# Setup SPARK configuration with HADOOP environment variables
RUN cp $SPARK_HOME/conf/spark-env.sh.template $SPARK_HOME/conf/spark-env.sh
# https://spark.apache.org/docs/latest/configuration.html#inheriting-hadoop-cluster-configuration
RUN echo "HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop" >> $SPARK_HOME/conf/spark-env.sh

EXPOSE 7077 8080 8081 4040

CMD ["sh"]
