namenode:
    image: ypenglyn/hadoop:2.6.5 
    ports:
        - 50070:50070
    command: hdfs namenode
    hostname: hdfs-namenode

datanode:
    image: ypenglyn/hadoop:2.6.5
    command: hdfs datanode
    ports:
        - 50075
    links:
        - namenode:hdfs-namenode

secondarynamenode:
    image: ypenglyn/hadoop:2.6.5
    command: hdfs secondarynamenode
    ports:
        - 50090:50090
    links:
        - namenode:hdfs-namenode
    hostname: hdfs-secondarynamenode

sparkmaster:
    image: ypenglyn/spark:2.1.0
    command: spark-class org.apache.spark.deploy.master.Master -h spark-master
    ports:
        - 7077:7077
        - 6066:6066
        - 8080:8080
        - 4040:4040
    links:
        - namenode:hdfs-namenode
    hostname: spark-master

sparkslave:
    image: ypenglyn/spark:2.1.0
    command: spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    ports:
        - 8081
    links:
        - namenode:hdfs-namenode
        - sparkmaster:spark-master

client:
    image: ypenglyn/env:0.0.1
    links:
        - namenode:hdfs-namenode
        - sparkmaster:spark-master
    hostname: spark-in-action
    volumes:
        - ./volume:/workspace/volume
